---
- name: Creates directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0775'
  loop:
    - "{{ nginx_home }}"
    - "{{ nginx_home }}/html"
    - "{{ nginx_logs }}"
    - "{{ nginx_conf }}/sites-enabled"

- name: Copy nginx configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
  loop:
    - { src: 'conf', dest: '{{ nginx_home }}' }
    - { src: 'cert', dest: '{{ nginx_home }}' }
    # - { src: 'nginx/', dest: '{{ nginx_conf }}/sites-enabled' }

- name: Copy and template files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0644'
    backup: true
  loop:
    - { src: '.env.j2', dest: '{{ nginx_home }}/.env' }
    - { src: 'docker-compose.yml.j2', dest: '{{ nginx_home }}/docker-compose.yml' }
    - { src: 'default.conf.j2', dest: '{{ nginx_conf }}/sites-enabled/default.conf' }

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  become: true
